#!/bin/bash
sh /tmp/MYSQL/mysql.sh;
echo "APACHE konfigürasyonları yapılandırılıyor...";
echo "export APACHE_RUN_USER=$SUDO_USER;export APACHE_RUN_GROUP=$SUDO_USER;" >> /etc/apache2/envvars
chown -R $SUDO_USER:$SUDO_USER /var/lock/apache2
a2enmod headers;
a2enmod rewrite;
cp /tmp/APACHE/zkitapeditoru_apache.conf /etc/apache2/sites-available/zkitapeditoru_apache.conf;
echo "127.0.0.1	zkitapeditoru.com" >> /etc/hosts;
a2ensite zkitapeditoru_apache.conf;
service apache2 reload;
service apache2 restart;

chmod -R 777 /var/www/zkitapeditoru/serialized
chmod -R 777 /var/www/zkitapeditoru/uploads
chmod 777 /var/log/epubtopdf

architecture=`getconf LONG_BIT`;


echo "NODEJS kuruluyor...";
nodejs=`which node`;
if [ "$nodejs" == "" ]; then
	cp -r /tmp/NODEJS/node-$architecture/bin/* /bin/
	cp -r /tmp/NODEJS/node-$architecture/include/* /include/
	cp -r /tmp/NODEJS/node-$architecture/lib/* /lib/
fi


echo "COWORKING kuruluyor...";
cd /tmp/NODEJS/coworking/;
sh cowork_install;
cd /var/www/coworking;

npm config set registry http://registry.npmjs.org/;
echo "SOCKET.IO kuruluyor..."
npm install socket.io;
service cowork restart;



if [ "$architecture" == "32" ]; then
	cp /tmp/ZKITAPEDITORU/zkitapeditoru_32 /usr/bin/zkitapeditoru;
	chmod -R 777 /var/lib/cef-32/;
else
	cp /tmp/ZKITAPEDITORU/zkitapeditoru_64 /usr/bin/zkitapeditoru;
	chmod -R 777 /var/lib/cef-64/;
fi

#libudev check for the ubuntu versions which is >=14.04
if [ ! -f /lib/$(arch)-linux-gnu/libudev.so.0 ]; then
	ln -sf /lib/$(arch)-linux-gnu/libudev.so.1 /lib/$(arch)-linux-gnu/libudev.so.0
fi


chmod 755 /usr/bin/zkitapeditoru;

echo "MASAÜSTÜ kısayolu oluşturuluyor...";
cp -rf /usr/share/applications/zkitapeditoru.desktop /home/$SUDO_USER/Masaüstü/;
chown $SUDO_USER:$SUDO_USER /home/$SUDO_USER/Masaüstü/zkitapeditoru.desktop;

echo "LEPUB formatı sisteme tanıtılıyor...";
update-mime-database /usr/share/mime;

